name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Backend
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Backend Dependencies
        run: |
          cd hrms-backend
          npm install

      - name: Run Backend Tests
        run: |
          cd hrms-backend
          npm test

      - name: Build Backend
        run: |
          cd hrms-backend
          npm run build

      # Frontend
      - name: Install Frontend Dependencies
        run: |
          cd hrms-frontend
          npm install

      - name: Run Frontend Tests
        run: |
          cd hrms-frontend
          npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build Frontend
        run: |
          cd hrms-frontend
          npm run build